### ISSUE TITLE
Не работают кнопки

### ISSUE THREAD

**Issue by aleksandrkanaev** [DigneZzZ/sub-page#5]
Не работает ни одна кнопка скопировать и кнопка скопировать все в разделе ссылки

**Comment by DigneZzZ** [comment]
> Не работает ни одна кнопка скопировать и кнопка скопировать все в разделе ссылки

Для работы кнопок копирования нужно чтобы были активны SSL сертификаты на странице, это ограничения http/https

**Comment by aleksandrkanaev** [comment]
Вон как, спасибо, не знал!

**Comment by aleksandrkanaev** [comment]
Был запуск без SSL
